### SweebApp - Dataset Preparation and Feature Engineering 📊🧠

In this phase of the project, three distinct datasets were selected and combined in order to build a more comprehensive and diverse data source. Each dataset contained network- and URL-related information, but with varying formats and feature distributions.

Two types of datasets will be created :

# 1. Structured Dataset (Tabular Data)

This version includes engineered features extracted from URLs (such as length, number of dots, and special characters) and will be used with classical machine learning models like Random Forest

To ensure consistency, all datasets were individually processed using custom preprocessing functions developed specifically for this project. These functions performed tasks such as:

 * `url_format()`: extracting structured features from raw URLs (e.g., length, number of dots, path length, protocol type) identifying suspicious patterns (e.g., presence of specific keywords, unusual characters)

 * `get_data_trainable()`: preprocess and transform a dataset into a structured format suitable for machine learning tasks, specifically for training and testing purposes

 * `create_final_dataset()`: standardizing the format across all datasets

Additionally, for datasets that included explicit attack-type labels, these were transformed into a unified classification scheme consisting of two categories: **Threat** OR **Safe**

# 2. Text-Based Dataset (NLP Dataset)

A second version of the dataset will retain the raw URL strings along with their corresponding labels. This dataset will be used for fine-tuning a transformer-based model (URLBERT) that operates directly on textual input and learns patterns automatically.


Finally, both datasets will be exported as .csv files and used in a subsequent phase of the project for model training and evaluation.

A comparative analysis will be conducted between **traditional machine learning models** & **transformer-based models**.

Datasets used :

 * **Data_1** : https://www.kaggle.com/datasets/dhrubangtalukdar/cybersecurity-threat-detection-dataset

 * **Data_2** : https://www.kaggle.com/datasets/taruntiwarihp/phishing-site-urls?select=phishing_site_urls.csv

 * **Data_3** : https://www.kaggle.com/datasets/sid321axn/malicious-urls-dataset

 ## 1. Structured Dataset (Tabular Data)

In [1]:
import kagglehub

path_data1 = kagglehub.dataset_download("dhrubangtalukdar/cybersecurity-threat-detection-dataset")

print("Path to dataset files:", path_data1)

Path to dataset files: C:\Users\CprAlin\.cache\kagglehub\datasets\dhrubangtalukdar\cybersecurity-threat-detection-dataset\versions\3

In [2]:
path_data2 = kagglehub.dataset_download("taruntiwarihp/phishing-site-urls")

print("Path to dataset files:", path_data2)

Path to dataset files: C:\Users\CprAlin\.cache\kagglehub\datasets\taruntiwarihp\phishing-site-urls\versions\1

In [3]:
path_data3 = kagglehub.dataset_download("sid321axn/malicious-urls-dataset")

print("Path to dataset files:", path_data3)

Path to dataset files: C:\Users\CprAlin\.cache\kagglehub\datasets\sid321axn\malicious-urls-dataset\versions\1

In [4]:
import pandas as pd

dataset1 = pd.read_csv(path_data1 + "/cybersecurity.csv")

In [5]:
dataset1.head()

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,188.176.27.165,253.240.113.218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,False,0,benign
1,2025-10-01 00:23:43,68.59.26.43,212.75.38.111,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,False,0,benign
2,2025-10-01 00:25:46,119.204.243.78,90.28.90.234,14948,1433,TCP,316502,38571,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,NaN,False,0,benign
3,2025-10-01 00:27:21,122.119.194.175,175.140.78.230,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,False,0,benign
4,2025-10-01 00:40:09,181.199.242.68,55.99.177.69,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,False,0,benign

In [6]:
dataset1.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            10000 non-null  str
 1   src_ip               10000 non-null  str
 2   dst_ip               10000 non-null  str
 3   src_port             10000 non-null  int64
 4   dst_port             10000 non-null  int64
 5   protocol             10000 non-null  str
 6   bytes_sent           10000 non-null  int64
 7   bytes_received       10000 non-null  int64
 8   user_agent           10000 non-null  str
 9   url                  6768 non-null   str
 10  is_internal_traffic  10000 non-null  bool
 11  label                10000 non-null  int64
 12  attack_type          10000 non-null  str
dtypes: bool(1), int64(5), str(7)
memory usage: 2.6 MB

In [7]:
dataset2 = pd.read_csv(path_data2 + "/phishing_site_urls.csv")

In [8]:
dataset2.info()

<class 'pandas.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   URL     549346 non-null  str
 1   Label   549346 non-null  str
dtypes: str(2)
memory usage: 36.9 MB

In [9]:
dataset2.head()

                                                 URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad

In [10]:
dataset3 = pd.read_csv(path_data3 + "/malicious_phish.csv")

In [11]:
dataset3.info()

<class 'pandas.DataFrame'>
RangeIndex: 651191 entries, 0 to 651190
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   url     651191 non-null  str
 1   type    651191 non-null  str
dtypes: str(2)
memory usage: 51.6 MB

In [12]:
dataset3.head()

                                                 url        type
0                                   br-icloud.com.br    phishing
1                mp3raid.com/music/krizz_kaliko.html      benign
2                    bopsecrets.org/rexroth/cr/1.htm      benign
3  http://www.garage-pirenne.be/index.php?option=...  defacement
4  http://adventure-nicaragua.net/index.php?optio...  defacement

In [13]:
import operator as op
from urllib.parse import urlsplit
from sklearn.preprocessing import StandardScaler

top_tlds = ["com","cloud","shop","io","icu","info","pro","online","org","net","edu","co","ro"]
suspicious_words = ["login","verify","secure","account","update","bank","signin","password"]

def url_format(url):
  try:
    parsed_url = urlsplit(url)

    return {
      'url_length' : len(url),
      'num_dots' : url.count('.'),
      'num_slash' : url.count('/'),
      'https_protocol' : int(parsed_url.scheme == "https"),
      'num_special_char_domain' : str(parsed_url.netloc).count(r'[^A-Za-z0-9-]'),
      'suspicious_word_domain' : int(any(word in parsed_url.netloc.lower() for word in suspicious_words)),
      'top_tld' : int(parsed_url.netloc.split(".")[-1] in top_tlds),
      'len_path' : len(parsed_url.path),
      'suspicious_char_path' : int(any(word in parsed_url.path.lower() for word in suspicious_words))
    }
  except Exception:
    return None

In [14]:
def get_data_trainable(data, url_column="url", columns=None,one_hot=None):
  '''
    This function will return data prepared for split into training and test.

    Params :
      - data : the Dataset to be transformed
      - columns : to remove some columns from the Dataset
      - one_hot : columns that need to be one-hot encoded
      - numeric_cols : columns that need to be normalized
      - url_column : the main column to apply 'url_format'
  '''
  if data is None:
    return

  data = data.dropna()
  if columns is not None:
    data = data.drop(columns=columns)

  if data[url_column] is not None:
    urls_data = data[url_column].apply(url_format).apply(pd.Series)

  if one_hot is not None:
    data = pd.get_dummies(data, columns=one_hot, drop_first=True)

  data = data.drop(url_column, axis='columns')

  df_final = pd.concat([data,urls_data], axis=1)

  return df_final

In [15]:
dataset1.head()

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,188.176.27.165,253.240.113.218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,False,0,benign
1,2025-10-01 00:23:43,68.59.26.43,212.75.38.111,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,False,0,benign
2,2025-10-01 00:25:46,119.204.243.78,90.28.90.234,14948,1433,TCP,316502,38571,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,NaN,False,0,benign
3,2025-10-01 00:27:21,122.119.194.175,175.140.78.230,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,False,0,benign
4,2025-10-01 00:40:09,181.199.242.68,55.99.177.69,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,False,0,benign

In [16]:
dataset1_trainable = get_data_trainable(dataset1, columns=["timestamp","src_ip","src_port","dst_ip","dst_port","protocol","bytes_sent","bytes_received","user_agent","is_internal_traffic","label"], one_hot=["attack_type"])

In [17]:
dataset1_trainable.head()

,attack_type_brute-force,attack_type_c2,attack_type_command-injection,attack_type_credential-stuffing,attack_type_ddos,attack_type_exploit-attempt,attack_type_port-scan,attack_type_sql-injection,attack_type_xss,url_length,num_dots,num_slash,https_protocol,num_special_char_domain,suspicious_word_domain,top_tld,len_path,suspicious_char_path
0,False,False,False,False,False,False,False,False,False,36,1,3,1,0,0,0,6,1
1,False,False,False,False,False,False,False,False,False,56,3,5,1,0,0,1,20,0
3,False,False,False,False,False,False,False,False,False,41,1,3,1,0,0,0,11,0
4,False,False,False,False,False,False,False,False,False,47,3,3,1,0,0,1,11,0
6,False,False,False,False,False,False,False,False,False,38,2,3,1,0,1,0,1,0

In [18]:
dataset1_trainable.info()

<class 'pandas.DataFrame'>
Index: 6768 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   attack_type_brute-force          6768 non-null   bool
 1   attack_type_c2                   6768 non-null   bool
 2   attack_type_command-injection    6768 non-null   bool
 3   attack_type_credential-stuffing  6768 non-null   bool
 4   attack_type_ddos                 6768 non-null   bool
 5   attack_type_exploit-attempt      6768 non-null   bool
 6   attack_type_port-scan            6768 non-null   bool
 7   attack_type_sql-injection        6768 non-null   bool
 8   attack_type_xss                  6768 non-null   bool
 9   url_length                       6768 non-null   int64
 10  num_dots                         6768 non-null   int64
 11  num_slash                        6768 non-null   int64
 12  https_protocol                   6768 non-null   int64
 13  num_special_char_domain          6768 non-null   int64
 14  suspicious_word_domain           6768 non-null   int64
 15  top_tld                          6768 non-null   int64
 16  len_path                         6768 non-null   int64
 17  suspicious_char_path             6768 non-null   int64
dtypes: bool(9), int64(9)
memory usage: 588.2 KB

In [19]:
dataset2.head()

                                                 URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad

In [20]:
dataset2.info()

<class 'pandas.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   URL     549346 non-null  str
 1   Label   549346 non-null  str
dtypes: str(2)
memory usage: 36.9 MB

In [21]:
dataset2_trainable = get_data_trainable(dataset2, url_column="URL",one_hot=["Label"])

In [22]:
dataset2_trainable.info()

<class 'pandas.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Label_good               549346 non-null  bool
 1   url_length               549346 non-null  int64
 2   num_dots                 549346 non-null  int64
 3   num_slash                549346 non-null  int64
 4   https_protocol           549346 non-null  int64
 5   num_special_char_domain  549346 non-null  int64
 6   suspicious_word_domain   549346 non-null  int64
 7   top_tld                  549346 non-null  int64
 8   len_path                 549346 non-null  int64
 9   suspicious_char_path     549346 non-null  int64
dtypes: bool(1), int64(9)
memory usage: 38.2 MB

In [23]:
dataset2_trainable.head()

,Label_good,url_length,num_dots,num_slash,https_protocol,num_special_char_domain,suspicious_word_domain,top_tld,len_path,suspicious_char_path
0,False,225,6,10,0,0,0,0,134,1
1,False,81,5,4,0,0,0,0,81,0
2,False,177,7,11,0,0,0,0,177,1
3,False,60,6,2,0,0,0,0,60,0
4,False,116,1,10,0,0,0,0,79,0

In [24]:
dataset3.info()

<class 'pandas.DataFrame'>
RangeIndex: 651191 entries, 0 to 651190
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   url     651191 non-null  str
 1   type    651191 non-null  str
dtypes: str(2)
memory usage: 51.6 MB

In [25]:
dataset3.head()

                                                 url        type
0                                   br-icloud.com.br    phishing
1                mp3raid.com/music/krizz_kaliko.html      benign
2                    bopsecrets.org/rexroth/cr/1.htm      benign
3  http://www.garage-pirenne.be/index.php?option=...  defacement
4  http://adventure-nicaragua.net/index.php?optio...  defacement

In [26]:
dataset3_trainable = get_data_trainable(dataset3, one_hot=["type"])

In [27]:
dataset3_trainable.info()

<class 'pandas.DataFrame'>
RangeIndex: 651191 entries, 0 to 651190
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   type_defacement          651191 non-null  bool
 1   type_malware             651191 non-null  bool
 2   type_phishing            651191 non-null  bool
 3   url_length               651191 non-null  int64
 4   num_dots                 651191 non-null  int64
 5   num_slash                651191 non-null  int64
 6   https_protocol           651191 non-null  int64
 7   num_special_char_domain  651191 non-null  int64
 8   suspicious_word_domain   651191 non-null  int64
 9   top_tld                  651191 non-null  int64
 10  len_path                 651191 non-null  int64
 11  suspicious_char_path     651191 non-null  int64
dtypes: bool(3), int64(9)
memory usage: 46.6 MB

In [28]:
dataset3_trainable.head()

,type_defacement,type_malware,type_phishing,url_length,num_dots,num_slash,https_protocol,num_special_char_domain,suspicious_word_domain,top_tld,len_path,suspicious_char_path
0,False,False,True,16,2,0,0,0,0,0,16,0
1,False,False,False,35,2,2,0,0,0,0,35,0
2,False,False,False,31,2,3,0,0,0,0,31,0
3,True,False,False,88,3,3,0,0,0,0,10,0
4,True,False,False,235,2,3,0,0,0,1,10,0

In [29]:
threat_types = ["threat","safe"]
main_cols = ['suspicious_char_path','len_path','top_tld','suspicious_word_domain','num_special_char_domain','https_protocol','num_slash','num_dots','url_length']

def create_final_dataset(dataset, detection_cols=None):
  '''
    This function standardize all datasets to a common data type.

    Params :
      - dataset : Set the dataset to be transformed
      - detection_cols : Insert here columns wich scope is to detect if is threat or not
  '''

  if dataset is None:
    return


  if not detection_cols:
    print("Please provide detection_cols")

  main_data = dataset[main_cols].copy()
  feature_change = dataset[detection_cols].copy()
  feature_change["is_threat"] = feature_change[detection_cols].any(axis=1).map({True : "threat", False : "safe"})
  feature_change = feature_change["is_threat"]
  final_dataset = pd.concat([main_data, feature_change],axis=1)

  return final_dataset

In [30]:
dataset3_trainable.head(1)

,type_defacement,type_malware,type_phishing,url_length,num_dots,num_slash,https_protocol,num_special_char_domain,suspicious_word_domain,top_tld,len_path,suspicious_char_path
0,False,False,True,16,2,0,0,0,0,0,16,0

In [31]:
final_dataset3 = create_final_dataset(dataset=dataset3_trainable, detection_cols=["type_defacement",	"type_malware",	"type_phishing"])

In [32]:
final_dataset3.head(10)

,suspicious_char_path,len_path,top_tld,suspicious_word_domain,num_special_char_domain,https_protocol,num_slash,num_dots,url_length,is_threat
0,0,16,0,0,0,0,0,2,16,threat
1,0,35,0,0,0,0,2,2,35,safe
2,0,31,0,0,0,0,3,2,31,safe
3,0,10,0,0,0,0,3,3,88,threat
4,0,10,1,0,0,0,3,2,235,threat
5,0,100,1,0,0,0,5,2,118,safe
6,0,45,0,0,0,0,6,2,45,safe
7,0,19,0,0,0,0,1,1,46,safe
8,0,15,1,0,0,0,3,2,44,threat
9,0,45,0,0,0,0,2,1,45,safe

In [33]:
final_dataset1 = create_final_dataset(dataset=dataset1_trainable, detection_cols=["attack_type_brute-force",	"attack_type_c2",	"attack_type_command-injection",	"attack_type_credential-stuffing",	"attack_type_ddos",	"attack_type_exploit-attempt",	"attack_type_port-scan",	"attack_type_sql-injection",	"attack_type_xss"])

In [34]:
final_dataset1.head(10)

,suspicious_char_path,len_path,top_tld,suspicious_word_domain,num_special_char_domain,https_protocol,num_slash,num_dots,url_length,is_threat
0,1,6,0,0,0,1,3,1,36,safe
1,0,20,1,0,0,1,5,3,56,safe
3,0,11,0,0,0,1,3,1,41,safe
4,0,11,1,0,0,1,3,3,47,safe
6,0,1,0,1,0,1,3,2,38,safe
7,0,11,0,0,0,1,3,1,41,safe
8,0,6,0,1,0,1,3,2,43,safe
10,0,20,1,0,0,1,5,3,52,safe
16,1,13,1,0,0,1,3,3,45,safe
18,0,13,0,1,0,1,4,2,50,safe

In [35]:
dataset2_trainable.head(1)

,Label_good,url_length,num_dots,num_slash,https_protocol,num_special_char_domain,suspicious_word_domain,top_tld,len_path,suspicious_char_path
0,False,225,6,10,0,0,0,0,134,1

In [36]:
final_dataset2 = create_final_dataset(dataset2_trainable, detection_cols=["Label_good"])

In [37]:
final_dataset2.head(10)

,suspicious_char_path,len_path,top_tld,suspicious_word_domain,num_special_char_domain,https_protocol,num_slash,num_dots,url_length,is_threat
0,1,134,0,0,0,0,10,6,225,safe
1,0,81,0,0,0,0,4,5,81,safe
2,1,177,0,0,0,0,11,7,177,safe
3,0,60,0,0,0,0,2,6,60,safe
4,0,79,0,0,0,0,10,1,116,safe
5,0,36,0,0,0,0,1,3,36,safe
6,0,61,0,0,0,0,2,2,61,safe
7,0,60,0,0,0,0,6,5,60,safe
8,0,19,0,0,0,0,1,1,19,safe
9,1,100,0,0,0,0,10,4,193,safe

In [38]:
final_dataset1.info()

<class 'pandas.DataFrame'>
Index: 6768 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   suspicious_char_path     6768 non-null   int64
 1   len_path                 6768 non-null   int64
 2   top_tld                  6768 non-null   int64
 3   suspicious_word_domain   6768 non-null   int64
 4   num_special_char_domain  6768 non-null   int64
 5   https_protocol           6768 non-null   int64
 6   num_slash                6768 non-null   int64
 7   num_dots                 6768 non-null   int64
 8   url_length               6768 non-null   int64
 9   is_threat                6768 non-null   str
dtypes: int64(9), str(1)
memory usage: 609.4 KB

In [39]:
final_dataset2.info()

<class 'pandas.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   suspicious_char_path     549346 non-null  int64
 1   len_path                 549346 non-null  int64
 2   top_tld                  549346 non-null  int64
 3   suspicious_word_domain   549346 non-null  int64
 4   num_special_char_domain  549346 non-null  int64
 5   https_protocol           549346 non-null  int64
 6   num_slash                549346 non-null  int64
 7   num_dots                 549346 non-null  int64
 8   url_length               549346 non-null  int64
 9   is_threat                549346 non-null  str
dtypes: int64(9), str(1)
memory usage: 44.8 MB

In [40]:
final_dataset3.info()

<class 'pandas.DataFrame'>
RangeIndex: 651191 entries, 0 to 651190
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   suspicious_char_path     651191 non-null  int64
 1   len_path                 651191 non-null  int64
 2   top_tld                  651191 non-null  int64
 3   suspicious_word_domain   651191 non-null  int64
 4   num_special_char_domain  651191 non-null  int64
 5   https_protocol           651191 non-null  int64
 6   num_slash                651191 non-null  int64
 7   num_dots                 651191 non-null  int64
 8   url_length               651191 non-null  int64
 9   is_threat                651191 non-null  str
dtypes: int64(9), str(1)
memory usage: 52.7 MB

In [41]:
final_dataset1 = pd.Series()

In [42]:


final_dataset = pd.concat([final_dataset1, final_dataset2, final_dataset3],ignore_index=True)

In [43]:
final_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200537 entries, 0 to 1200536
Data columns (total 11 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   0                        0 non-null        object
 1   suspicious_char_path     1200537 non-null  float64
 2   len_path                 1200537 non-null  float64
 3   top_tld                  1200537 non-null  float64
 4   suspicious_word_domain   1200537 non-null  float64
 5   num_special_char_domain  1200537 non-null  float64
 6   https_protocol           1200537 non-null  float64
 7   num_slash                1200537 non-null  float64
 8   num_dots                 1200537 non-null  float64
 9   url_length               1200537 non-null  float64
 10  is_threat                1200537 non-null  str
dtypes: float64(9), object(1), str(1)
memory usage: 106.7+ MB

In [44]:
final_dataset.head(1)

,0,suspicious_char_path,len_path,top_tld,suspicious_word_domain,num_special_char_domain,https_protocol,num_slash,num_dots,url_length,is_threat
0,NaN,1.0,134.0,0.0,0.0,0.0,0.0,10.0,6.0,225.0,safe

In [45]:
final_dataset = pd.get_dummies(final_dataset, columns=["is_threat"], drop_first=True)

In [46]:
final_dataset.head(1)

,0,suspicious_char_path,len_path,top_tld,suspicious_word_domain,num_special_char_domain,https_protocol,num_slash,num_dots,url_length,is_threat_threat
0,NaN,1.0,134.0,0.0,0.0,0.0,0.0,10.0,6.0,225.0,False

In [47]:
final_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200537 entries, 0 to 1200536
Data columns (total 11 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   0                        0 non-null        object
 1   suspicious_char_path     1200537 non-null  float64
 2   len_path                 1200537 non-null  float64
 3   top_tld                  1200537 non-null  float64
 4   suspicious_word_domain   1200537 non-null  float64
 5   num_special_char_domain  1200537 non-null  float64
 6   https_protocol           1200537 non-null  float64
 7   num_slash                1200537 non-null  float64
 8   num_dots                 1200537 non-null  float64
 9   url_length               1200537 non-null  float64
 10  is_threat_threat         1200537 non-null  bool
dtypes: bool(1), float64(9), object(1)
memory usage: 92.7+ MB

In [50]:
#final_dataset.to_csv("sweeb_phishing_dataset.csv", index=False)
small_data = final_dataset.sample(n=40000, random_state=42)
small_data.to_csv("sweeb_phishing_dataset.csv", index=False)

In [51]:
dataset_8 = final_dataset.sample(n=800000, random_state=42)
dataset_8.info()

<class 'pandas.DataFrame'>
Index: 800000 entries, 1008941 to 533188
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   0                        0 non-null       object
 1   suspicious_char_path     800000 non-null  float64
 2   len_path                 800000 non-null  float64
 3   top_tld                  800000 non-null  float64
 4   suspicious_word_domain   800000 non-null  float64
 5   num_special_char_domain  800000 non-null  float64
 6   https_protocol           800000 non-null  float64
 7   num_slash                800000 non-null  float64
 8   num_dots                 800000 non-null  float64
 9   url_length               800000 non-null  float64
 10  is_threat_threat         800000 non-null  bool
dtypes: bool(1), float64(9), object(1)
memory usage: 67.9+ MB

## 2. Text-Based Dataset (NLP Dataset)

In [ ]:
dataset1.head(1)

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,188.176.27.165,253.240.113.218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,False,0,benign

In [ ]:
nlp_dataset1 = dataset1[["url","attack_type"]]

In [ ]:
nlp_dataset1.head(10)

                                                 url attack_type
0               https://webmail.corp/login?id=385071      benign
1  https://portal.example.org/owa/auth/logon.aspx...      benign
2                                                NaN      benign
3          https://webmail.corp/phpmyadmin?id=114701      benign
4    https://portal.example.org/config.php?id=345569      benign
5                                                NaN      benign
6             https://internal.bank.local/?id=432022      benign
7          https://webmail.corp/phpmyadmin?id=957608      benign
8        https://internal.bank.local/admin?id=567716      benign
9                                                NaN      benign

In [ ]:
nlp_dataset1.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   url          6768 non-null   str
 1   attack_type  10000 non-null  str
dtypes: str(2)
memory usage: 501.8 KB

In [ ]:
nlp_dataset1 = nlp_dataset1.dropna()

In [ ]:
nlp_dataset1.info()

<class 'pandas.DataFrame'>
Index: 6768 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   url          6768 non-null   str
 1   attack_type  6768 non-null   str
dtypes: str(2)
memory usage: 484.9 KB

In [ ]:
nlp_dataset1 = pd.get_dummies(nlp_dataset1, columns=["attack_type"], drop_first=True)
nlp_dataset1.head(1)

,url,attack_type_brute-force,attack_type_c2,attack_type_command-injection,attack_type_credential-stuffing,attack_type_ddos,attack_type_exploit-attempt,attack_type_port-scan,attack_type_sql-injection,attack_type_xss
0,https://webmail.corp/login?id=385071,False,False,False,False,False,False,False,False,False

In [ ]:
threat_types = ["threat","safe"]

def create_final_nlp_dataset(dataset, detection_cols=None, main_cols=None):
  '''
    This function standardize all datasets to a common data type.

    Params :
      - dataset : Set the dataset to be transformed
      - detection_cols : Insert here columns wich scope is to detect if is threat or not
      - main_cols : Insert here columns wich scope is to keep
  '''

  if dataset is None:
    return


  if not detection_cols:
    print("Please provide detection_cols")

  if not main_cols:
    print("Please provide main_cols")

  main_data = dataset[main_cols].copy()
  feature_change = dataset[detection_cols].copy()
  feature_change["is_threat"] = feature_change[detection_cols].any(axis=1).map({True : 1, False : 0})
  feature_change = feature_change["is_threat"]
  final_dataset = pd.concat([main_data, feature_change],axis=1)

  return final_dataset

In [ ]:
final_nlp_dataset1 = create_final_nlp_dataset(dataset=nlp_dataset1,
                                              detection_cols=["attack_type_brute-force",	"attack_type_c2",	"attack_type_command-injection",
                                                              "attack_type_credential-stuffing",	"attack_type_ddos",	"attack_type_exploit-attempt",
                                                              "attack_type_port-scan",	"attack_type_sql-injection",	"attack_type_xss"],
                                              main_cols=["url"])

In [ ]:
final_nlp_dataset1.info()

<class 'pandas.DataFrame'>
Index: 6768 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   url        6768 non-null   str
 1   is_threat  6768 non-null   int64
dtypes: int64(1), str(1)
memory usage: 443.2 KB

In [ ]:
final_nlp_dataset1.head(10)

                                                  url  is_threat
0                https://webmail.corp/login?id=385071          0
1   https://portal.example.org/owa/auth/logon.aspx...          0
3           https://webmail.corp/phpmyadmin?id=114701          0
4     https://portal.example.org/config.php?id=345569          0
6              https://internal.bank.local/?id=432022          0
7           https://webmail.corp/phpmyadmin?id=957608          0
8         https://internal.bank.local/admin?id=567716          0
10  https://api.service.io/owa/auth/logon.aspx?id=...          0
16      https://api.service.io/wp-login.php?id=407810          0
18  https://internal.bank.local/manager/html?id=20...          0

In [ ]:
dataset2.head(1)

                                                 URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad

In [ ]:
nlp_dataset2 = dataset2[["URL","Label"]]

In [ ]:
nlp_dataset2.info()

<class 'pandas.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   URL     549346 non-null  str
 1   Label   549346 non-null  str
dtypes: str(2)
memory usage: 36.9 MB

In [ ]:
nlp_dataset2 = nlp_dataset2.rename(columns={"URL" : "url"})
nlp_dataset2.head(1)

                                                 url Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad

In [ ]:
final_nlp_dataset2 = create_final_nlp_dataset(nlp_dataset2,["Label"],["url"])

In [ ]:
final_nlp_dataset2.info()

<class 'pandas.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   url        549346 non-null  str
 1   is_threat  549346 non-null  int64
dtypes: int64(1), str(1)
memory usage: 35.0 MB

In [ ]:
final_nlp_dataset2.head(2)

                                                 url  is_threat
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...          1
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...          1

In [ ]:
dataset3.head(1)

                url      type
0  br-icloud.com.br  phishing

In [ ]:
nlp_dataset3 = pd.get_dummies(dataset3, columns=["type"], drop_first=True)
nlp_dataset3.head(2)

,url,type_defacement,type_malware,type_phishing
0,br-icloud.com.br,False,False,True
1,mp3raid.com/music/krizz_kaliko.html,False,False,False

In [ ]:
final_nlp_dataset3 = create_final_nlp_dataset(nlp_dataset3,["type_defacement",	"type_malware",	"type_phishing"],["url"])

In [ ]:
final_nlp_dataset3.info()

<class 'pandas.DataFrame'>
RangeIndex: 651191 entries, 0 to 651190
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   url        651191 non-null  str
 1   is_threat  651191 non-null  int64
dtypes: int64(1), str(1)
memory usage: 47.3 MB

In [ ]:
final_nlp_dataset3.head(10)

                                                 url  is_threat
0                                   br-icloud.com.br          1
1                mp3raid.com/music/krizz_kaliko.html          0
2                    bopsecrets.org/rexroth/cr/1.htm          0
3  http://www.garage-pirenne.be/index.php?option=...          1
4  http://adventure-nicaragua.net/index.php?optio...          1
5  http://buzzfil.net/m/show-art/ils-etaient-loin...          0
6      espn.go.com/nba/player/_/id/3457/brandon-rush          0
7     yourbittorrent.com/?q=anthony-hamilton-soulife          0
8       http://www.pashminaonline.com/pure-pashminas          1
9      allmusic.com/album/crazy-from-the-heat-r16990          0

In [ ]:
final_nlp_dataset = pd.concat([final_nlp_dataset1, final_nlp_dataset2, final_nlp_dataset3], ignore_index=True)

In [ ]:
final_nlp_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1207305 entries, 0 to 1207304
Data columns (total 2 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   url        1207305 non-null  str
 1   is_threat  1207305 non-null  int64
dtypes: int64(1), str(1)
memory usage: 82.7 MB

In [ ]:
final_nlp_dataset.head(10)

                                                 url  is_threat
0               https://webmail.corp/login?id=385071          0
1  https://portal.example.org/owa/auth/logon.aspx...          0
2          https://webmail.corp/phpmyadmin?id=114701          0
3    https://portal.example.org/config.php?id=345569          0
4             https://internal.bank.local/?id=432022          0
5          https://webmail.corp/phpmyadmin?id=957608          0
6        https://internal.bank.local/admin?id=567716          0
7  https://api.service.io/owa/auth/logon.aspx?id=...          0
8      https://api.service.io/wp-login.php?id=407810          0
9  https://internal.bank.local/manager/html?id=20...          0

In [ ]:
final_nlp_dataset

                                                       url  is_threat
0                     https://webmail.corp/login?id=385071          0
1        https://portal.example.org/owa/auth/logon.aspx...          0
2                https://webmail.corp/phpmyadmin?id=114701          0
3          https://portal.example.org/config.php?id=345569          0
4                   https://internal.bank.local/?id=432022          0
...                                                    ...        ...
1207300            xbox360.ign.com/objects/850/850402.html          1
1207301       games.teamxbox.com/xbox-360/1860/Dead-Space/          1
1207302         www.gamespot.com/xbox360/action/deadspace/          1
1207303      en.wikipedia.org/wiki/Dead_Space_(video_game)          1
1207304          www.angelfire.com/goth/devilmaycrytonite/          1

[1207305 rows x 2 columns]

                                                    url  is_threat
0                  https://webmail.corp/login?id=385071          0
1     https://portal.example.org/owa/auth/logon.aspx...          0
2             https://webmail.corp/phpmyadmin?id=114701          0
3       https://portal.example.org/config.php?id=345569          0
4                https://internal.bank.local/?id=432022          0
...                                                 ...        ...
1032  https://portal.example.org/api/v1/users?id=579993          0
1033     https://internal.bank.local/test.php?id=864528          0
1034                    https://webmail.corp/?id=703149          0
1035           https://webmail.corp/dashboard?id=133512          0
1036          https://app.company.in/test.php?id=599684          0

[1000 rows x 2 columns]

In [ ]:
#final_nlp_dataset.to_csv("sweeb_phishing_nlp_dataset.csv", index=False)