### SweebApp - Dataset Preparation and Feature Engineering 📊🧠

In this phase of the project, three distinct datasets were selected and combined in order to build a more comprehensive and diverse data source. Each dataset contained network- and URL-related information, but with varying formats and feature distributions.

To ensure consistency, all datasets were individually processed using custom preprocessing functions developed specifically for this project. These functions performed tasks such as:

 * `url_format()`: extracting structured features from raw URLs (e.g., length, number of dots, path length, protocol type) identifying suspicious patterns (e.g., presence of specific keywords, unusual characters)

 * `get_data_trainable()`: preprocess and transform a dataset into a structured format suitable for machine learning tasks, specifically for training and testing purposes

 * `create_final_dataset()`: standardizing the format across all datasets

Additionally, for datasets that included explicit attack-type labels, these were transformed into a unified classification scheme consisting of two categories: **Threat** OR **Safe**

After preprocessing, the datasets were merged into a single unified DataFrame.

Finally, this processed dataset will be exported as a .csv file, which will be used in a subsequent project phase for ***transfer learning***.

Datasets used :

 * **Data_1** : https://www.kaggle.com/datasets/dhrubangtalukdar/cybersecurity-threat-detection-dataset

 * **Data_2** : https://www.kaggle.com/datasets/taruntiwarihp/phishing-site-urls?select=phishing_site_urls.csv

 * **Data_3** : https://www.kaggle.com/datasets/sid321axn/malicious-urls-dataset

In [80]:
import kagglehub

path_data1 = kagglehub.dataset_download("dhrubangtalukdar/cybersecurity-threat-detection-dataset")

print("Path to dataset files:", path_data1)

Using Colab cache for faster access to the 'cybersecurity-threat-detection-dataset' dataset.
Path to dataset files: /kaggle/input/cybersecurity-threat-detection-dataset

In [81]:
path_data2 = kagglehub.dataset_download("taruntiwarihp/phishing-site-urls")

print("Path to dataset files:", path_data2)

Using Colab cache for faster access to the 'phishing-site-urls' dataset.
Path to dataset files: /kaggle/input/phishing-site-urls

In [82]:
path_data3 = kagglehub.dataset_download("sid321axn/malicious-urls-dataset")

print("Path to dataset files:", path_data3)

Using Colab cache for faster access to the 'malicious-urls-dataset' dataset.
Path to dataset files: /kaggle/input/malicious-urls-dataset

In [83]:
import pandas as pd

dataset1 = pd.read_csv(path_data1 + "/cybersecurity.csv")

In [84]:
dataset1.head()

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,188.176.27.165,253.240.113.218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,False,0,benign
1,2025-10-01 00:23:43,68.59.26.43,212.75.38.111,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,False,0,benign
2,2025-10-01 00:25:46,119.204.243.78,90.28.90.234,14948,1433,TCP,316502,38571,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,NaN,False,0,benign
3,2025-10-01 00:27:21,122.119.194.175,175.140.78.230,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,False,0,benign
4,2025-10-01 00:40:09,181.199.242.68,55.99.177.69,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,False,0,benign

In [85]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            10000 non-null  object
 1   src_ip               10000 non-null  object
 2   dst_ip               10000 non-null  object
 3   src_port             10000 non-null  int64
 4   dst_port             10000 non-null  int64
 5   protocol             10000 non-null  object
 6   bytes_sent           10000 non-null  int64
 7   bytes_received       10000 non-null  int64
 8   user_agent           10000 non-null  object
 9   url                  6768 non-null   object
 10  is_internal_traffic  10000 non-null  bool
 11  label                10000 non-null  int64
 12  attack_type          10000 non-null  object
dtypes: bool(1), int64(5), object(7)
memory usage: 947.4+ KB

In [86]:
dataset2 = pd.read_csv(path_data2 + "/phishing_site_urls.csv")

In [87]:
dataset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   URL     549346 non-null  object
 1   Label   549346 non-null  object
dtypes: object(2)
memory usage: 8.4+ MB

In [88]:
dataset2.head()

                                                 URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad

In [89]:
dataset3 = pd.read_csv(path_data3 + "/malicious_phish.csv")

In [90]:
dataset3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651191 entries, 0 to 651190
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   url     651191 non-null  object
 1   type    651191 non-null  object
dtypes: object(2)
memory usage: 9.9+ MB

In [91]:
dataset3.head()

                                                 url        type
0                                   br-icloud.com.br    phishing
1                mp3raid.com/music/krizz_kaliko.html      benign
2                    bopsecrets.org/rexroth/cr/1.htm      benign
3  http://www.garage-pirenne.be/index.php?option=...  defacement
4  http://adventure-nicaragua.net/index.php?optio...  defacement

In [92]:
import operator as op
from urllib.parse import urlsplit
from sklearn.preprocessing import StandardScaler

top_tlds = ["com","cloud","shop","io","icu","info","pro","online","org","net","edu","co","ro"]
suspicious_words = ["login","verify","secure","account","update","bank","signin","password"]

def url_format(url):
  try:
    parsed_url = urlsplit(url)

    return {
      'url_length' : len(url),
      'num_dots' : url.count('.'),
      'num_slash' : url.count('/'),
      'https_protocol' : int(parsed_url.scheme == "https"),
      'num_special_char_domain' : str(parsed_url.netloc).count(r'[^A-Za-z0-9-]'),
      'suspicious_word_domain' : int(any(word in parsed_url.netloc.lower() for word in suspicious_words)),
      'top_tld' : int(parsed_url.netloc.split(".")[-1] in top_tlds),
      'len_path' : len(parsed_url.path),
      'suspicious_char_path' : int(any(word in parsed_url.path.lower() for word in suspicious_words))
    }
  except Exception:
    return None

In [93]:
def get_data_trainable(data, url_column="url", columns=None,one_hot=None):
  '''
    This function will return data prepared for split into training and test.

    Params :
      - data : the Dataset to be transformed
      - columns : to remove some columns from the Dataset
      - one_hot : columns that need to be one-hot encoded
      - numeric_cols : columns that need to be normalized
      - url_column : the main column to apply 'url_format'
  '''
  if data is None:
    return

  data = data.dropna()
  if columns is not None:
    data = data.drop(columns=columns)

  if data[url_column] is not None:
    urls_data = data[url_column].apply(url_format).apply(pd.Series)

  if one_hot is not None:
    data = pd.get_dummies(data, columns=one_hot, drop_first=True)

  data = data.drop(url_column, axis='columns')

  df_final = pd.concat([data,urls_data], axis=1)

  return df_final

In [94]:
dataset1.head()

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,188.176.27.165,253.240.113.218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,False,0,benign
1,2025-10-01 00:23:43,68.59.26.43,212.75.38.111,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,False,0,benign
2,2025-10-01 00:25:46,119.204.243.78,90.28.90.234,14948,1433,TCP,316502,38571,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,NaN,False,0,benign
3,2025-10-01 00:27:21,122.119.194.175,175.140.78.230,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,False,0,benign
4,2025-10-01 00:40:09,181.199.242.68,55.99.177.69,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,False,0,benign

In [95]:
dataset1_trainable = get_data_trainable(dataset1, columns=["timestamp","src_ip","src_port","dst_ip","dst_port","protocol","bytes_sent","bytes_received","user_agent","is_internal_traffic","label"], one_hot=["attack_type"])

In [96]:
dataset1_trainable.head()

,attack_type_brute-force,attack_type_c2,attack_type_command-injection,attack_type_credential-stuffing,attack_type_ddos,attack_type_exploit-attempt,attack_type_port-scan,attack_type_sql-injection,attack_type_xss,url_length,num_dots,num_slash,https_protocol,num_special_char_domain,suspicious_word_domain,top_tld,len_path,suspicious_char_path
0,False,False,False,False,False,False,False,False,False,36,1,3,1,0,0,0,6,1
1,False,False,False,False,False,False,False,False,False,56,3,5,1,0,0,1,20,0
3,False,False,False,False,False,False,False,False,False,41,1,3,1,0,0,0,11,0
4,False,False,False,False,False,False,False,False,False,47,3,3,1,0,0,1,11,0
6,False,False,False,False,False,False,False,False,False,38,2,3,1,0,1,0,1,0

In [97]:
dataset1_trainable.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6768 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   attack_type_brute-force          6768 non-null   bool
 1   attack_type_c2                   6768 non-null   bool
 2   attack_type_command-injection    6768 non-null   bool
 3   attack_type_credential-stuffing  6768 non-null   bool
 4   attack_type_ddos                 6768 non-null   bool
 5   attack_type_exploit-attempt      6768 non-null   bool
 6   attack_type_port-scan            6768 non-null   bool
 7   attack_type_sql-injection        6768 non-null   bool
 8   attack_type_xss                  6768 non-null   bool
 9   url_length                       6768 non-null   int64
 10  num_dots                         6768 non-null   int64
 11  num_slash                        6768 non-null   int64
 12  https_protocol                   6768 non-null   int64
 13  num_special_char_domain          6768 non-null   int64
 14  suspicious_word_domain           6768 non-null   int64
 15  top_tld                          6768 non-null   int64
 16  len_path                         6768 non-null   int64
 17  suspicious_char_path             6768 non-null   int64
dtypes: bool(9), int64(9)
memory usage: 588.2 KB

In [98]:
dataset2.head()

                                                 URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad

In [99]:
dataset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   URL     549346 non-null  object
 1   Label   549346 non-null  object
dtypes: object(2)
memory usage: 8.4+ MB

In [100]:
dataset2_trainable = get_data_trainable(dataset2, url_column="URL",one_hot=["Label"])

In [101]:
dataset2_trainable.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Label_good               549346 non-null  bool
 1   url_length               549346 non-null  int64
 2   num_dots                 549346 non-null  int64
 3   num_slash                549346 non-null  int64
 4   https_protocol           549346 non-null  int64
 5   num_special_char_domain  549346 non-null  int64
 6   suspicious_word_domain   549346 non-null  int64
 7   top_tld                  549346 non-null  int64
 8   len_path                 549346 non-null  int64
 9   suspicious_char_path     549346 non-null  int64
dtypes: bool(1), int64(9)
memory usage: 38.2 MB

In [102]:
dataset2_trainable.head()

,Label_good,url_length,num_dots,num_slash,https_protocol,num_special_char_domain,suspicious_word_domain,top_tld,len_path,suspicious_char_path
0,False,225,6,10,0,0,0,0,134,1
1,False,81,5,4,0,0,0,0,81,0
2,False,177,7,11,0,0,0,0,177,1
3,False,60,6,2,0,0,0,0,60,0
4,False,116,1,10,0,0,0,0,79,0

In [103]:
dataset3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651191 entries, 0 to 651190
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   url     651191 non-null  object
 1   type    651191 non-null  object
dtypes: object(2)
memory usage: 9.9+ MB

In [104]:
dataset3.head()

                                                 url        type
0                                   br-icloud.com.br    phishing
1                mp3raid.com/music/krizz_kaliko.html      benign
2                    bopsecrets.org/rexroth/cr/1.htm      benign
3  http://www.garage-pirenne.be/index.php?option=...  defacement
4  http://adventure-nicaragua.net/index.php?optio...  defacement

In [105]:
dataset3_trainable = get_data_trainable(dataset3, one_hot=["type"])

In [106]:
dataset3_trainable.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651191 entries, 0 to 651190
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   type_defacement          651191 non-null  bool
 1   type_malware             651191 non-null  bool
 2   type_phishing            651191 non-null  bool
 3   url_length               651191 non-null  int64
 4   num_dots                 651191 non-null  int64
 5   num_slash                651191 non-null  int64
 6   https_protocol           651191 non-null  int64
 7   num_special_char_domain  651191 non-null  int64
 8   suspicious_word_domain   651191 non-null  int64
 9   top_tld                  651191 non-null  int64
 10  len_path                 651191 non-null  int64
 11  suspicious_char_path     651191 non-null  int64
dtypes: bool(3), int64(9)
memory usage: 46.6 MB

In [107]:
dataset3_trainable.head()

,type_defacement,type_malware,type_phishing,url_length,num_dots,num_slash,https_protocol,num_special_char_domain,suspicious_word_domain,top_tld,len_path,suspicious_char_path
0,False,False,True,16,2,0,0,0,0,0,16,0
1,False,False,False,35,2,2,0,0,0,0,35,0
2,False,False,False,31,2,3,0,0,0,0,31,0
3,True,False,False,88,3,3,0,0,0,0,10,0
4,True,False,False,235,2,3,0,0,0,1,10,0

In [108]:
threat_types = ["threat","safe"]
main_cols = ['suspicious_char_path','len_path','top_tld','suspicious_word_domain','num_special_char_domain','https_protocol','num_slash','num_dots','url_length']

def create_final_dataset(dataset, detection_cols=None):
  '''
    This function standardize all datasets to a common data type.

    Params :
      - dataset : Set the dataset to be transformed
      - detection_cols : Insert here columns wich scope is to detect if is threat or not
  '''

  if dataset is None:
    return


  if not detection_cols:
    print("Please provide detection_cols")

  main_data = dataset[main_cols].copy()
  feature_change = dataset[detection_cols].copy()
  feature_change["is_threat"] = feature_change[detection_cols].any(axis=1).map({True : "threat", False : "safe"})
  feature_change = feature_change["is_threat"]
  final_dataset = pd.concat([main_data, feature_change],axis=1)

  return final_dataset

In [109]:
dataset3_trainable.head(1)

,type_defacement,type_malware,type_phishing,url_length,num_dots,num_slash,https_protocol,num_special_char_domain,suspicious_word_domain,top_tld,len_path,suspicious_char_path
0,False,False,True,16,2,0,0,0,0,0,16,0

In [110]:
final_dataset3 = create_final_dataset(dataset=dataset3_trainable, detection_cols=["type_defacement",	"type_malware",	"type_phishing"])

In [111]:
final_dataset3.head(10)

,suspicious_char_path,len_path,top_tld,suspicious_word_domain,num_special_char_domain,https_protocol,num_slash,num_dots,url_length,is_threat
0,0,16,0,0,0,0,0,2,16,threat
1,0,35,0,0,0,0,2,2,35,safe
2,0,31,0,0,0,0,3,2,31,safe
3,0,10,0,0,0,0,3,3,88,threat
4,0,10,1,0,0,0,3,2,235,threat
5,0,100,1,0,0,0,5,2,118,safe
6,0,45,0,0,0,0,6,2,45,safe
7,0,19,0,0,0,0,1,1,46,safe
8,0,15,1,0,0,0,3,2,44,threat
9,0,45,0,0,0,0,2,1,45,safe

In [112]:
final_dataset1 = create_final_dataset(dataset=dataset1_trainable, detection_cols=["attack_type_brute-force",	"attack_type_c2",	"attack_type_command-injection",	"attack_type_credential-stuffing",	"attack_type_ddos",	"attack_type_exploit-attempt",	"attack_type_port-scan",	"attack_type_sql-injection",	"attack_type_xss"])

In [113]:
final_dataset1.head(10)

,suspicious_char_path,len_path,top_tld,suspicious_word_domain,num_special_char_domain,https_protocol,num_slash,num_dots,url_length,is_threat
0,1,6,0,0,0,1,3,1,36,safe
1,0,20,1,0,0,1,5,3,56,safe
3,0,11,0,0,0,1,3,1,41,safe
4,0,11,1,0,0,1,3,3,47,safe
6,0,1,0,1,0,1,3,2,38,safe
7,0,11,0,0,0,1,3,1,41,safe
8,0,6,0,1,0,1,3,2,43,safe
10,0,20,1,0,0,1,5,3,52,safe
16,1,13,1,0,0,1,3,3,45,safe
18,0,13,0,1,0,1,4,2,50,safe

In [114]:
dataset2_trainable.head(1)

,Label_good,url_length,num_dots,num_slash,https_protocol,num_special_char_domain,suspicious_word_domain,top_tld,len_path,suspicious_char_path
0,False,225,6,10,0,0,0,0,134,1

In [115]:
final_dataset2 = create_final_dataset(dataset2_trainable, detection_cols=["Label_good"])

In [116]:
final_dataset2.head(10)

,suspicious_char_path,len_path,top_tld,suspicious_word_domain,num_special_char_domain,https_protocol,num_slash,num_dots,url_length,is_threat
0,1,134,0,0,0,0,10,6,225,safe
1,0,81,0,0,0,0,4,5,81,safe
2,1,177,0,0,0,0,11,7,177,safe
3,0,60,0,0,0,0,2,6,60,safe
4,0,79,0,0,0,0,10,1,116,safe
5,0,36,0,0,0,0,1,3,36,safe
6,0,61,0,0,0,0,2,2,61,safe
7,0,60,0,0,0,0,6,5,60,safe
8,0,19,0,0,0,0,1,1,19,safe
9,1,100,0,0,0,0,10,4,193,safe

In [117]:
final_dataset1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6768 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   suspicious_char_path     6768 non-null   int64
 1   len_path                 6768 non-null   int64
 2   top_tld                  6768 non-null   int64
 3   suspicious_word_domain   6768 non-null   int64
 4   num_special_char_domain  6768 non-null   int64
 5   https_protocol           6768 non-null   int64
 6   num_slash                6768 non-null   int64
 7   num_dots                 6768 non-null   int64
 8   url_length               6768 non-null   int64
 9   is_threat                6768 non-null   object
dtypes: int64(9), object(1)
memory usage: 581.6+ KB

In [118]:
final_dataset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   suspicious_char_path     549346 non-null  int64
 1   len_path                 549346 non-null  int64
 2   top_tld                  549346 non-null  int64
 3   suspicious_word_domain   549346 non-null  int64
 4   num_special_char_domain  549346 non-null  int64
 5   https_protocol           549346 non-null  int64
 6   num_slash                549346 non-null  int64
 7   num_dots                 549346 non-null  int64
 8   url_length               549346 non-null  int64
 9   is_threat                549346 non-null  object
dtypes: int64(9), object(1)
memory usage: 41.9+ MB

In [119]:
final_dataset3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651191 entries, 0 to 651190
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   suspicious_char_path     651191 non-null  int64
 1   len_path                 651191 non-null  int64
 2   top_tld                  651191 non-null  int64
 3   suspicious_word_domain   651191 non-null  int64
 4   num_special_char_domain  651191 non-null  int64
 5   https_protocol           651191 non-null  int64
 6   num_slash                651191 non-null  int64
 7   num_dots                 651191 non-null  int64
 8   url_length               651191 non-null  int64
 9   is_threat                651191 non-null  object
dtypes: int64(9), object(1)
memory usage: 49.7+ MB

In [ ]:
final_dataset1 = pd.Series()

In [122]:


final_dataset = pd.concat([final_dataset1, final_dataset2, final_dataset3],ignore_index=True)

In [123]:
final_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1207305 entries, 0 to 1207304
Data columns (total 10 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   suspicious_char_path     1207305 non-null  int64
 1   len_path                 1207305 non-null  int64
 2   top_tld                  1207305 non-null  int64
 3   suspicious_word_domain   1207305 non-null  int64
 4   num_special_char_domain  1207305 non-null  int64
 5   https_protocol           1207305 non-null  int64
 6   num_slash                1207305 non-null  int64
 7   num_dots                 1207305 non-null  int64
 8   url_length               1207305 non-null  int64
 9   is_threat                1207305 non-null  object
dtypes: int64(9), object(1)
memory usage: 92.1+ MB

In [124]:
final_dataset.head(1)

,suspicious_char_path,len_path,top_tld,suspicious_word_domain,num_special_char_domain,https_protocol,num_slash,num_dots,url_length,is_threat
0,1,6,0,0,0,1,3,1,36,safe

In [125]:
final_dataset = pd.get_dummies(final_dataset, columns=["is_threat"], drop_first=True)

In [126]:
final_dataset.head(1)

,suspicious_char_path,len_path,top_tld,suspicious_word_domain,num_special_char_domain,https_protocol,num_slash,num_dots,url_length,is_threat_threat
0,1,6,0,0,0,1,3,1,36,False

In [127]:
final_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1207305 entries, 0 to 1207304
Data columns (total 10 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   suspicious_char_path     1207305 non-null  int64
 1   len_path                 1207305 non-null  int64
 2   top_tld                  1207305 non-null  int64
 3   suspicious_word_domain   1207305 non-null  int64
 4   num_special_char_domain  1207305 non-null  int64
 5   https_protocol           1207305 non-null  int64
 6   num_slash                1207305 non-null  int64
 7   num_dots                 1207305 non-null  int64
 8   url_length               1207305 non-null  int64
 9   is_threat_threat         1207305 non-null  bool
dtypes: bool(1), int64(9)
memory usage: 84.1 MB

In [128]:
final_dataset.to_csv("sweeb_phishing_dataset.csv")